#!/usr/bin/env bash
# Regenerates scripts/demo.sh — a self-contained terminal demo whose frames are
# real cc-status-dash renders captured here and embedded (base64) so the demo
# needs no Node/Bun at playback time (VHS records `bash scripts/demo.sh`).
#
# Usage:  bun run build && bash scripts/build-demo.sh
# Then:   render the GIF with docs/demo.tape (see docs/DEVELOPMENT.md).
set -euo pipefail
cd "$(dirname "$0")/.."

ENTRY="dist/index.js"
INPUT="sample-input.json"
OUT="scripts/demo.sh"
export COLUMNS=118

# caption|cli-args  — each renders sample-input.json through the entry point.
FRAMES=(
  "essential · hud-clean (default theme)|--preset essential"
  "oneline · everything on a single line|--preset oneline"
  "full · identity + all metrics + live activity|--preset full"
  "dashboard · four layers|--preset dashboard"
  "max · five layers|--preset max"
  "theme: tokyo-night|--preset full --theme tokyo-night"
  "theme: gruvbox|--preset full --theme gruvbox"
  "theme: nord|--preset full --theme nord"
  "powerline style|--preset git --theme tokyo-night"
  "capsule style|--preset capsule --theme nord"
  "minimal · one line|--preset minimal --theme gruvbox"
)

{
  echo '#!/usr/bin/env bash'
  echo '# AUTO-GENERATED by scripts/build-demo.sh — do not edit by hand.'
  echo '# Self-contained: frames are real cc-status-dash renders (base64) + captions.'
  echo 'set -u'
  echo 'BOLD=$(printf "\033[1m"); CYAN=$(printf "\033[36m"); DIM=$(printf "\033[2m"); RST=$(printf "\033[0m")'
  echo 'clear'
  echo 'printf "\n  %scc-status-dash%s  %s— ccstatusline’s brain, Claude HUD’s face%s\n\n" "$BOLD$CYAN" "$RST" "$DIM" "$RST"'
  echo 'sleep 2'
  for f in "${FRAMES[@]}"; do
    cap="${f%%|*}"; args="${f#*|}"
    b64=$(node "$ENTRY" $args < "$INPUT" | base64 | tr -d '\n')
    echo 'clear'
    printf 'printf "\\n  %%s▸ %s%%s\\n\\n" "$DIM" "$RST"\n' "$cap"
    echo "printf '  '; echo '${b64}' | base64 -d | sed 's/^/  /'"
    echo 'printf "\n"'
    echo 'sleep 2'
  done
  echo 'clear'
  echo 'printf "\n  %sInstall:%s  /plugin install cc-status-dash   ·   npx cc-status-dash@latest\n\n" "$BOLD" "$RST"'
  echo 'sleep 2'
} > "$OUT"

chmod +x "$OUT"
echo "wrote $OUT ($(wc -l < "$OUT") lines)"
