#!/usr/bin/env bash
# AUTO-GENERATED by scripts/build-demo.sh — do not edit by hand.
# Self-contained: frames are real cc-status-dash renders (base64) + captions.
set -u
BOLD=$(printf "\033[1m"); CYAN=$(printf "\033[36m"); DIM=$(printf "\033[2m"); RST=$(printf "\033[0m")
clear
printf "\n  %scc-status-dash%s  %s— ccstatusline’s brain, Claude HUD’s face%s\n\n" "$BOLD$CYAN" "$RST" "$DIM" "$RST"
sleep 2
clear
printf "\n  %s▸ essential · hud-clean (default theme)%s\n\n" "$DIM" "$RST"
printf '  '; echo 'IBtbMW0bWzM2beKcsSBPcHVzIDQuOBtbMG0gIBtbMm3ilIIbWzBtICAbWzMzbWNjLXN0YXR1cy1kYXNoG1swbSAKIBtbMm1Db250ZXh0IBtbMG0bWzMybeKWiOKWiOKWiOKWiOKWiBtbMG0bWzkwbeKWkeKWkeKWkeKWkeKWkRtbMG0gG1szMm01NCUgbGVmdBtbMG0gIBtbMm3ilIIbWzBtICAbWzJtNWggG1swbRtbOTRtMzglG1swbRtbMzJtIOKHozI3OCUbWzBtIAo=' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %s▸ oneline · everything on a single line%s\n\n" "$DIM" "$RST"
printf '  '; echo 'IBtbMW0bWzM2beKcsSBPcHVzIDQuOBtbMG0gIBtbMm3ilIIbWzBtICAbWzMzbWNjLXN0YXR1cy1kYXNoG1swbSAgG1sybeKUghtbMG0gIBtbMm1Db250ZXh0IBtbMG0bWzMybTU0JSBsZWZ0G1swbSAgG1sybeKUghtbMG0gIBtbMm01aCAbWzBtG1s5NG0zOCUbWzBtG1szMm0g4oejMjc4JRtbMG0gIBtbMm3ilIIbWzBtICAbWzMybSQzLjQyG1swbSAK' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %s▸ full · identity + all metrics + live activity%s\n\n" "$DIM" "$RST"
printf '  '; echo 'G1sxbRtbMm0bWzQ2bSAg4pyxIE9wdXMgNC44ICAbWzBtG1szNm0bWzQzbe6CsBtbMG0bWzFtG1sybRtbNDNtICBwcm9qZWN0cy9jYy1zdGF0dXMtZGFzaCAgG1swbRtbMzNt7oKwG1swbQogG1sybUNvbnRleHQgG1swbRtbMzJt4paI4paI4paI4paI4paIG1swbRtbOTBt4paR4paR4paR4paR4paRG1swbSAbWzMybTU0JSBsZWZ0G1swbSAgG1sybeKUghtbMG0gIBtbMm01aCAbWzBtG1s5NG0zOCUbWzBtG1szMm0g4oejMjc4JRtbMG0gIBtbMm3ilIIbWzBtICAbWzMybSQzLjQyG1swbSAK' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %s▸ dashboard · four layers%s\n\n" "$DIM" "$RST"
printf '  '; echo 'G1sxbRtbMm0bWzQ2bSAg4pyxIE9wdXMgNC44ICAbWzBtG1szNm0bWzQzbe6CsBtbMG0bWzFtG1sybRtbNDNtICBwcm9qZWN0cy9jYy1zdGF0dXMtZGFzaCAgG1swbRtbMzNt7oKwG1swbQogG1sybUNvbnRleHQgG1swbRtbMzJt4paI4paI4paI4paI4paIG1swbRtbOTBt4paR4paR4paR4paR4paRG1swbSAbWzMybTU0JSBsZWZ0G1swbSAgG1sybeKUghtbMG0gIBtbMzJtJDMuNDIbWzBtIAogG1sybTVoIBtbMG0bWzk0bTM4JRtbMG0bWzMybSDih6MyNzglG1swbSAgG1sybeKUghtbMG0gIBtbMm03ZCAbWzBtG1szM202MSUbWzBtIAo=' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %s▸ max · five layers%s\n\n" "$DIM" "$RST"
printf '  '; echo 'G1sxbRtbMm0bWzQ2bSAg4pyxIE9wdXMgNC44ICAbWzBtG1szNm0bWzQzbe6CsBtbMG0bWzFtG1sybRtbNDNtICBwcm9qZWN0cy9jYy1zdGF0dXMtZGFzaCAgG1swbRtbMzNt7oKwG1swbQogG1sybUNvbnRleHQgG1swbRtbMzJt4paI4paI4paI4paI4paIG1swbRtbOTBt4paR4paR4paR4paR4paRG1swbSAbWzMybTU0JSBsZWZ0G1swbSAgG1sybeKUghtbMG0gIBtbMzJtJDMuNDIbWzBtIAogG1sybTVoIBtbMG0bWzk0bTM4JRtbMG0bWzMybSDih6MyNzglG1swbSAKIBtbMm03ZCAbWzBtG1szM202MSUbWzBtICAbWzJt4pSCG1swbSAgG1szMm0kMy40MhtbMG0gCg==' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %s▸ theme: tokyo-night%s\n\n" "$DIM" "$RST"
printf '  '; echo 'G1sxbRtbMzg7Mjs4Njs5NTsxMzdtG1s0ODsyOzEyNTsyMDc7MjU1bSAg4pyxIE9wdXMgNC44ICAbWzBtG1szODsyOzEyNTsyMDc7MjU1bRtbNDg7MjsyMjQ7MTc1OzEwNG3ugrAbWzBtG1sxbRtbMzg7Mjs4Njs5NTsxMzdtG1s0ODsyOzIyNDsxNzU7MTA0bSAgcHJvamVjdHMvY2Mtc3RhdHVzLWRhc2ggIBtbMG0bWzM4OzI7MjI0OzE3NTsxMDRt7oKwG1swbQogG1szODsyOzg2Ozk1OzEzN21Db250ZXh0IBtbMG0bWzM4OzI7MTU4OzIwNjsxMDZt4paI4paI4paI4paI4paIG1swbRtbMzg7Mjs2NTs3MjsxMDRt4paR4paR4paR4paR4paRG1swbSAbWzM4OzI7MTU4OzIwNjsxMDZtNTQlIGxlZnQbWzBtICAbWzM4OzI7ODY7OTU7MTM3beKUghtbMG0gIBtbMzg7Mjs4Njs5NTsxMzdtNWggG1swbRtbMzg7MjsxMjI7MTYyOzI0N20zOCUbWzBtG1szODsyOzE1ODsyMDY7MTA2bSDih6MyNzglG1swbSAgG1szODsyOzg2Ozk1OzEzN23ilIIbWzBtICAbWzM4OzI7MTU4OzIwNjsxMDZtJDMuNDIbWzBtIAo=' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %s▸ theme: gruvbox%s\n\n" "$DIM" "$RST"
printf '  '; echo 'G1sxbRtbMzg7MjsxNDY7MTMxOzExNm0bWzQ4OzI7MTMxOzE2NTsxNTJtICDinLEgT3B1cyA0LjggIBtbMG0bWzM4OzI7MTMxOzE2NTsxNTJtG1s0ODsyOzI1MDsxODk7NDdt7oKwG1swbRtbMW0bWzM4OzI7MTQ2OzEzMTsxMTZtG1s0ODsyOzI1MDsxODk7NDdtICBwcm9qZWN0cy9jYy1zdGF0dXMtZGFzaCAgG1swbRtbMzg7MjsyNTA7MTg5OzQ3be6CsBtbMG0KIBtbMzg7MjsxNDY7MTMxOzExNm1Db250ZXh0IBtbMG0bWzM4OzI7MTg0OzE4NzszOG3ilojilojilojilojilogbWzBtG1szODsyOzgwOzczOzY5beKWkeKWkeKWkeKWkeKWkRtbMG0gG1szODsyOzE4NDsxODc7MzhtNTQlIGxlZnQbWzBtICAbWzM4OzI7MTQ2OzEzMTsxMTZt4pSCG1swbSAgG1szODsyOzE0NjsxMzE7MTE2bTVoIBtbMG0bWzM4OzI7MTMxOzE2NTsxNTJtMzglG1swbRtbMzg7MjsxODQ7MTg3OzM4bSDih6MyNzglG1swbSAgG1szODsyOzE0NjsxMzE7MTE2beKUghtbMG0gIBtbMzg7MjsxODQ7MTg3OzM4bSQzLjQyG1swbSAK' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %s▸ theme: nord%s\n\n" "$DIM" "$RST"
printf '  '; echo 'G1sxbRtbMzg7Mjs3Njs4NjsxMDZtG1s0ODsyOzEzNjsxOTI7MjA4bSAg4pyxIE9wdXMgNC44ICAbWzBtG1szODsyOzEzNjsxOTI7MjA4bRtbNDg7MjsyMzU7MjAzOzEzOW3ugrAbWzBtG1sxbRtbMzg7Mjs3Njs4NjsxMDZtG1s0ODsyOzIzNTsyMDM7MTM5bSAgcHJvamVjdHMvY2Mtc3RhdHVzLWRhc2ggIBtbMG0bWzM4OzI7MjM1OzIwMzsxMzlt7oKwG1swbQogG1szODsyOzc2Ozg2OzEwNm1Db250ZXh0IBtbMG0bWzM4OzI7MTYzOzE5MDsxNDBt4paI4paI4paI4paI4paIG1swbRtbMzg7Mjs1OTs2Njs4Mm3ilpHilpHilpHilpHilpEbWzBtIBtbMzg7MjsxNjM7MTkwOzE0MG01NCUgbGVmdBtbMG0gIBtbMzg7Mjs3Njs4NjsxMDZt4pSCG1swbSAgG1szODsyOzc2Ozg2OzEwNm01aCAbWzBtG1szODsyOzEyOTsxNjE7MTkzbTM4JRtbMG0bWzM4OzI7MTYzOzE5MDsxNDBtIOKHozI3OCUbWzBtICAbWzM4OzI7NzY7ODY7MTA2beKUghtbMG0gIBtbMzg7MjsxNjM7MTkwOzE0MG0kMy40MhtbMG0gCg==' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %s▸ powerline style%s\n\n" "$DIM" "$RST"
printf '  '; echo 'G1sxbRtbMzg7Mjs4Njs5NTsxMzdtG1s0ODsyOzEyNTsyMDc7MjU1bSAg4pyxIE9wdXMgNC44ICAbWzBtG1szODsyOzEyNTsyMDc7MjU1bRtbNDg7MjsyMjQ7MTc1OzEwNG3ugrAbWzBtG1sxbRtbMzg7Mjs4Njs5NTsxMzdtG1s0ODsyOzIyNDsxNzU7MTA0bSAgcHJvamVjdHMvY2Mtc3RhdHVzLWRhc2ggIBtbMG0bWzM4OzI7MjI0OzE3NTsxMDRt7oKwG1swbQogG1szODsyOzg2Ozk1OzEzN21Db250ZXh0IBtbMG0bWzM4OzI7MTU4OzIwNjsxMDZt4paI4paI4paI4paI4paIG1swbRtbMzg7Mjs2NTs3MjsxMDRt4paR4paR4paR4paR4paRG1swbSAbWzM4OzI7MTU4OzIwNjsxMDZtNTQlIGxlZnQbWzBtICAbWzM4OzI7ODY7OTU7MTM3beKUghtbMG0gIBtbMzg7Mjs4Njs5NTsxMzdtNWggG1swbRtbMzg7MjsxMjI7MTYyOzI0N20zOCUbWzBtG1szODsyOzE1ODsyMDY7MTA2bSDih6MyNzglG1swbSAK' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %s▸ capsule style%s\n\n" "$DIM" "$RST"
printf '  '; echo 'G1szODsyOzEzNjsxOTI7MjA4be6CthtbMG0bWzFtG1szODsyOzc2Ozg2OzEwNm0bWzQ4OzI7MTM2OzE5MjsyMDhtICDinLEgT3B1cyA0LjggIBtbMG0bWzM4OzI7MTM2OzE5MjsyMDht7oK0G1swbSAbWzM4OzI7MjM1OzIwMzsxMzlt7oK2G1swbRtbMW0bWzM4OzI7NzY7ODY7MTA2bRtbNDg7MjsyMzU7MjAzOzEzOW0gIGNjLXN0YXR1cy1kYXNoICAbWzBtG1szODsyOzIzNTsyMDM7MTM5be6CtBtbMG0KIBtbMzg7Mjs3Njs4NjsxMDZtQ29udGV4dCAbWzBtG1szODsyOzE2MzsxOTA7MTQwbeKWiOKWiOKWiOKWiOKWiBtbMG0bWzM4OzI7NTk7NjY7ODJt4paR4paR4paR4paR4paRG1swbSAbWzM4OzI7MTYzOzE5MDsxNDBtNTQlIGxlZnQbWzBtICAbWzM4OzI7NzY7ODY7MTA2beKUghtbMG0gIBtbMzg7Mjs3Njs4NjsxMDZtNWggG1swbRtbMzg7MjsxMjk7MTYxOzE5M20zOCUbWzBtG1szODsyOzE2MzsxOTA7MTQwbSDih6MyNzglG1swbSAK' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %s▸ minimal · one line%s\n\n" "$DIM" "$RST"
printf '  '; echo 'IBtbMW0bWzM4OzI7MTMxOzE2NTsxNTJt4pyxIE9wdXMgNC44G1swbSAgG1szODsyOzE0NjsxMzE7MTE2beKUghtbMG0gIBtbMzg7MjsxNDY7MTMxOzExNm1Db250ZXh0IBtbMG0bWzM4OzI7MTg0OzE4NzszOG01NCUgbGVmdBtbMG0gCg==' | base64 -d | sed 's/^/  /'
printf "\n"
sleep 2
clear
printf "\n  %sInstall:%s  /plugin install cc-status-dash   ·   npx cc-status-dash@latest\n\n" "$BOLD" "$RST"
sleep 2
